---
title: "E-02 Answers"
layout: page
output: 
    md_document:
        variant: markdown
---
> ### Challenge -- fitting the logistic equation
>
> * Take some time now to play around with those parameters. Can you come up with a 
>   better fit? (Make sure you run the whole batch of code again, to get new
>   values for the column `model_logistic_output`.)
> * It seems clear that we can't quite get this perfect either.  Why not?
>   Can you come up with any biological reasons why our logistic model isn't perfect?
> 

You may find it hard to get a perfect fit. Either you fit the initial growth well
but the later fit is poor, vice versa, or you can fit the very beginning and end 
but don't fit the growth well at intermediate times. With the logistic model we 
expect nearly exponential growth at first, then a relatively quick flattening in
population size as we approach $$K$$. Here instead we see that 
the population growth slows, but looks almost linear for a long while.

A few things to keep in mind to potentially explain this:

 * Because the data are not actually *live* cell counts, but instead are just
    measures of cell density in the fluid, our counts might be higher than the
    real population size at carrying capacity $$K$$.  So the slow increase phase
    that begins around time 10 hours might reflect a steady population, but with 
    an increasing number of dead cells floating around that are also being counted.
 * These microbes often have high DNA mutation rates, and some mutant 
    individuals might
    arise that can continue to flourish even when $$N$$ is near $$K$$. Increasing
    population growth at this point could potentially reflect evolution in action.
 * Our logistic model imposes a particular mathematical relation on the rate of slowing.
    It's simple, but there's no reason to be sure that it's the best. 
    We might need more parameters or different relationships between variables
    to be able to fit more realistic data.
 
The [phases section](https://en.wikipedia.org/wiki/Bacterial_growth#Phases) of
the "Bacterial growth" page on Wikipedia lays out another way to think about 
microbe growth rates in culture, and adds some nuance to our logistic-growth
thinking.

[Back to exploration](../../E-02-growth-rate-models)
