---
title: "R-03 Answers"
layout: page
output: 
    md_document:
        variant: markdown
---

> ### Challenge
>
> 1. Spread the `surveys` data frame with `year` as columns, `plot_id` 
>   as rows, and the
>   number of genera per plot as the values. You will need to summarize before
>   reshaping, and use the function `n_distinct()` to get the number of unique
>   genera within a particular chunk of data. It's a powerful function! See
>   `?n_distinct` for more.
> 
>       ```{r, eval=FALSE}
>       rich_time <- surveys %>%
>           group_by(plot_id, year) %>%
>           summarize(n_genera = n_distinct(genus)) %>%
>           spread(year, n_genera)
> 
>       head(rich_time)
>       ```
>
> 2. Now take that data frame and `gather()` it again, so each row is a unique
>    `plot_id` by `year` combination.
>
>       ```{r, eval=FALSE}
>       rich_time %>%
>           gather(year, n_genera, -plot_id)
>       ```
>
> 3. The `surveys` data set has
>    two measurement columns: `hindfoot_length` and `weight`.  This makes it
>    difficult to do things like look at the relationship between mean values of
>    each measurement per year in different plot types. Let's walk through a
>    common solution for this type of problem. First, use `gather()` to create a
>     dataset where we have a key column called `measurement` and a
>    `value` column that takes on the value of either `hindfoot_length` or
>    `weight`. *Hint*: You'll need to specify which columns are being gathered.
>
>       ```{r, eval=FALSE}
>       surveys_long <- surveys %>%
>           gather(measurement, value, hindfoot_length, weight)
>       ```
>
> 4. With this new data set, calculate the average of each
>    `measurement` in each `year` for each different `plot_type`. Then
>    `spread()` them into a data set with a column for `hindfoot_length` and
>    `weight`. *Hint*: You only need to specify the key and value
>    columns for `spread()`.
>
>       ```{r, eval=FALSE}
>       surveys_long %>%
>           group_by(year, measurement, plot_type) %>%
>           summarize(mean_value = mean(value, na.rm=TRUE)) %>%
>           spread(measurement, mean_value)
>       ```

[Back to reading](../../R-03-dplyr)